- name: Download and Configure Winlogbeat
  hosts: windows
  gather_facts: no

  tasks:
    - name: Download Winlogbeat
      win_get_url:
        url: https://artifacts.elastic.co/downloads/beats/winlogbeat/winlogbeat-7.17.9-windows-x86_64.zip
        dest: C:\Temp\winlogbeat.zip

    - name: Unzip Winlogbeat
      win_unzip:
        src: C:\Temp\winlogbeat.zip
        dest: C:\Program Files
        creates: C:\Program Files\winlogbeat

    - name: Copy custom winlogbeat.yml
      win_copy:
        src: /path/to/your/winlogbeat.yml
        dest: C:\Program Files\winlogbeat
        remote_src: yes

    - name: Replace winlogbeat.yml
      win_command:
        cmd: move /Y C:\Program Files\winlogbeat\winlogbeat.yml C:\Program Files\winlogbeat\winlogbeat.yml.bak
      register: result
      failed_when: false

    - name: Copy custom winlogbeat.yml
      win_copy:
        src: /path/to/your/winlogbeat.yml
        dest: C:\Program Files\winlogbeat
        remote_src: yes

    - name: Restart Winlogbeat service
      win_service:
        name: winlogbeat
        state: restarted
